<?php 
$val = "
********* relative *********,
みょうじ:last name,
なまえ:name,
かぞく:Family/Family Members,
こども:Children,
おかあさん:mother,
おとうさん:father,
りょうしん:Parents,
むすこ:son,
むすめ:daughter,
あね:older sister,
おに:older brother,
おとうと:Younger brother,
いもうと:Younger sister,
おじさん:Uncle,
おばさん:Aunt,
おじいさん:grandfather,
おばあさん:grandmother,
いとこ:cousin,
まご:Grandchild,
ともだち:friend,
しゅじん:Husband,
つま:Wife,



******* Occupations and Jobs ********,
せんせい:teacher,
がくせい:Student,
だいがくせい:College student,
かいしゃいん:employee,
ぎんこういん:banker,
いしゃ:doctor,
ろうどうしゃ:Worker,
かんごし:nurse,
べんごし:lawyer,
ジャーナリスト:journalist,
エンジニア:engineer,
あるばいと:part-time job,
むしょく:Unemployed,
コック:Cook,
シェフ:Chef,
パイロット:Pilot,




******* fruits *******,
くだもの:Fruit,
もも:Peach,
みかん:Mandarin Orange,
うめ:Plum,
りんご:Apple,
ぶどう:Grape,
すいか:Watermelon,
レモン:Lemon,
サクランボ:Cherry,
メロン:Melon,
バナナ:Banana,
オレンジ:Orange,
アボカド:Avocado,
ブルーベリー:Blueberry,
グレープフルーツ:Grapefruit,
ココナッツ:Coconut,
パパイヤ:Papaya,
アプリコット:Apricot,



******* Vegetables *******,
やさい:Vegetable/野菜,
だいこん:White Radish/大根,
にんじん:Carrot/人参,
キャベツ:Cabbage,
レタス:Lettuce,
ブロッコリー:Broccoli,
カリフラワー:Cauliflower,
ピーマン:Green Pepper,
パセリ:Parsley,
セロリ:Celery,
トマト:Tomato,
ジャガイモ:Potato,
サツマイモ:Sweet Potato,
キノコ:Mushroom/茸,
たまねぎ:Onion/玉葱,
わさび:Wasabi/山葵,
もやし:Bean Sprouts/萌やし,
ピーナッツ:Peanut,
オクラ:Okra,
レンコン:Lotus Root/蓮根,




******* Body Parts *******,
からだ:Body/体[body],
かお:Face/顔[body],
かみ:Hair/神[body],
みみ:Ear/耳[body],
め:Eye/目[body],
はな:Nose/花[body],
くち:Mouth/口[body],
くちびる:Lips/唇[body],
は:Teeth/歯[body],
くび:Neck/首[body],
かた:Shoulder/肩[body],
うで:Arm/腕[body],
て:Hand/手[body],
ゆび:Finger/指[body],
むね:Breast/Chest/胸[body],
はら:Stomach/腹[body],
ひざ:Knee/膝[body],
あし:Foot/Leg/足[body],
せなか:Back(of Body)/背中[body],
おしり:Buttocks/お尻[body],
はだ:Skin/肌[body],
ほね:Bone/骨[body],



******* Food *******,
たべもの:Food/食べ物[food],
りょうり:cooking Food[food],
あさごはん:Breakfast/朝御飯[food],
ひるごはん:Lunch/昼御飯[food],
ばんごはん:Dinner/晩御飯[food],
べんとう:Box Lunch/弁当[food],
ごはん:Meal/Cooked Rice/御飯[food],
さしみ:Sliced Raw Fish/刺身[food],
てんぷら:Tempura/Deep-fried food/天婦羅[food],
うなぎ:Eel/鰻[food],
とんカツ:Pork Cutlet/豚カツ[food],
すし:Sushi/寿司[food],
カレーライス:Curry and Rice[food],
おこのみやき:okonomiyaki/お好み焼き[food],
やきとり:Grilled Chicken/焼き鳥[food],
みそしる:Miso Soup/味噌汁[food],
ラーメン:ra-men Ramen[food],
うどん:udon/wheat noodles[food],
もち:Sticky Rice Cake/餅[food],
さかな:Fish/魚[food],
えび:Prawn/Shrimp/海老/蝦[food],
とうふ:Tofu/Bean Curd/豆腐[food],
たまご:Egg/卵[food],
しょうゆ:Soy Sauce/醤油[food],
あぶら:Oil/油[food],
さとう:Sugar/砂糖[food],
しお:Salt/塩[food],
こしょう:Pepper/胡椒[food],
かき:oyster/貝[food],
にぎり:nice ball[food],
ちゃわん:rice bowl[food],



******* Drinks *******,
のむ:to drink/飲む,
みず:Water/水,
おちゃ:Tea/お茶,
こうちゃ:Black Tea/紅茶,
ぎゅうにゅう:Milk/牛乳,
おさけ:Alcohol/Sake/お酒,
コーヒー:Coffee,
ココア:Cocoa/Hot Chocolate,
ジュース:Juice,
オレンジジュース:Orange Juice,
スムージー:Smoothie,
ソーダ:Soda,
コーラ:Cola,
ラムネ:Lemon Soda,
アルコール:Alcohol,
ワイン:Wine,
シェリー:Sherry (wine),
ビール:Beer,
ウイスキー:Whiskey,
スコッチ:Scotch Whisky,
ブランデー:Brandy,
シャンパン:Champagne,
ウォッカ:Vodka,
テキーラ:Tequila,




******* Sports *******,
うんどう:Exercise/Sport/運動,
スポーツ:Sport,
やきゅう:Baseball/野球,
すもう:Sumo Wrestling/相撲,
じゅうどう:Judo/柔道,
けんどう:Kendo/Japanese Fencing/剣道,
からて:Karate/空手,
ピンポン:Ping-pong/Table Tennis,
サッカー:Soccer,
テニス:Tennis,
ゴルフ:Golf,
バスケットボール:Basketball,
バレーボール:Volleyball,
ラグビー:Rugby,
バドミントン:Badminton,
ホッケー:Hockey,
ボーリング:Bowling,
ボクシング:Boxing,
レスリング:Wrestling,
サイクリング:Cycling,
ランニング:Running,
ジョギング:Jogging,
マラソン:Marathon,
ダンシング:Dancing,
スケー:Skating,
スキー:Skiing,
アーチェリー:Archery,
クリケット:Cricket,
エアロビクス:Aerobics,
ソフトボール:Softball,



******* House and furniture  *******,
いえ:House/家,
へや:Room/部屋,
リビングルーム:Living Room,
だいどころ:Kitchen/台所,
キッチン:Kitchen,
トイレ:Toilet,
バルコニー:Balcony,
ドア:Door,
かぎ:Key/鍵,
まど:Window/窓,
かがみ:Mirror/鏡,
テーブル:Table,
ソファー:Sofa/Couch,
ベッド:Bed,
テレビ:Television,
ラジオ:Radio,
ステレオ:Stereo,
ビデオ:Video,
カップ:Cup,
スプーン:Spoon,
フォーク:Fork,
ナイフ:Knife,
コンピューター:Computer,
パソコン:Personal Computer,
アパート:Apartment,
グラス:Glass,
コップ:Glass,




******* Clothes and Accessories *******,
きもの:Kimono/着物,
ゆかた:yukata/Japanese Summer Kimono/浴衣,
コート:Coat,
オーバー:Overcoat,
スーツ:Suit,
レインコート:Raincoat,
パンツ:Underpants/Underwear,
ジャケット:Jacket,
パジャマ:pajamas,
ブレザー:Blazer,
ブラウス:Blouse,
ドレス:Dress,
ワンピース:One-piece Dress,
ズボン:Trousers,
ショーツ:Shorts,
スラックス:Slacks,
ジーンズ:Jean,
スカート:Skirt,
T-シャツ:T-shirt,
セーター:Sweater,
イヤリング:Earring,
ネックレス:Necklace,
ネクタイ:Necktie,
スカーフ:Scarf,
ベルト:Belt,
スニーカー:Sneakers,
サンダル:Sandals,
ブーツ:Boots,
くつ:shoes,
ようふく:Western clothes,






******* Animals *******,
どうぶつ:Animal/動物,
ネズミ:Mouse/Rat/鼠,
ねこ:Cat/猫,
いぬ:Dog/犬,
とり:Bird/鳥,
スズメ:Sparrow/雀,
サル:Monkey/猿,
うし:Cow/Cattle/牛,
うま:Horse/馬,
ヒツジ:Sheep/羊,
ブタ:Pig/豚,
キツネ:Fox/狐,
タヌキ:Raccoon Dog/狸,
トラ:Tiger/虎,
さかな:Fish/魚,
イカ:Cuttlefish/Squid/烏賊,
カキ:Oyster/牡蠣,
カニ:Crab/蟹,
タコ:Octopus/蛸/章魚,
あり:Ant/蟻,
へび:snake/蛇,
ぶた:pig/豚,
か:mosquito/蚊,
パンダ:Panda,
カンガルー:Kangaroo,
ライオン:Lion,
チーター:Cheetah,
ペンギン:Penguin,
たぬき:raccon dog,
いのしし:wild boar,
たこ:kie/octpus:divided skirt,
ほたる:firely,
むし:insect,






******* Verbs *******,
する:To do[v],
です:To be[v],
なる:To become[v],
ある:There is (inanimate)[v],
いる:There is(living)[v],
いく:To go/行く[v],
いう:To say/言う[v],
みる:To see/見る[v],
くる:To come/来る[v],
たべる:To eat/食べる[v],
はなすはなす:to talk[v],
よむ:to read/読む[v],
かく:to write/書く[v],
わかる:to undrestand/分かる[v],



******* Anime vocab *******,
アニメ:Anime[anime],
マンガ:cartoon[anime],
かわいい:Cute[anime],
かっこいい:Cool[anime],
すごい:Wow!/Amazing![anime],
ヤバい:Uncool[anime],
マジで:Seriously/Really[anime],
うそ!:No way![anime],
ばか:Idiot[anime],
よし:Okay/let’s do this![anime],



******* Directions *******,
きた:North 北[directions],
みなみ:South 南[directions],
ひがし:East 東[directions],
にし:West 西[directions],
うえ:above/on/上[directions],
した:Below/下[directions],
ひだり:Left/左[directions],
みぎ:Right/右[directions],
なか:Inside/中[directions],
そと:Outside/外[directions],
まえ:In front/前[directions],
うしろ:Behind/後ろ[directions],


******* Country *******,
くに:Country/国,
ちゅうごく:China/中国,
にほん:Japan/日本,
にっぽん:Japan/日本,
きたちょうせん:North Korea/北朝鮮,
かんこく:South Korea/韓国,
アフリカ:Africa,
アジア:Asia,
ヨーロッパ:Europe,
アメリカ:America (USA),
オーストラリア:Australia,
ブラジル:Brazil,
カナダ:Canada,
デンマーク:Denmark,
エジプト:Egypt,
フランス:France,
フィンランド:Finland,
ドイツ:Germany,
ギリシャ:Greece,
アイスランド:Iceland,
イラン:Iran,
イラク:Iraq,
イスラエル:Israel,
イタリア:Italy,
マレーシア:Malaysia,
ノルウェー:Norway,
カタール:Qatar,
ロシア:Russia,
サウジアラビア:Saudi Arabia,
スペイン:Spain,
たいわん:Taiwan,
タイ:Thailand,
トルコ:Turkey,




******* Festivals and Events *******,
まつり:Festival/祭り,
しょうがつ:New Year/New Year's Day/正月,
はなみ:Cherry Blossom Viewing/花見,
はなび:Firework/花火,
ははのひ:Mother's Day/母の日,
ちちのひ:Father's Day/父の日,
たなばた:The Star Festival (July 7th)/七夕,
おぼん:Bon Festival (mid August)/お盆,
なつやすみ:Summer Vacation/夏休み,
たんじょうび:Birthday/誕生日,
ちゃのゆ: tea ceremony/茶の湯,
バレンタインデー:Valentine's Day,
ゴールデンウイーク:Golden Week,
クリスマス:Christmas,
ハロウィーン:Halloween,





******* store/places *******,
にくや:Butcher/Meat Shop/肉屋,
さかなや:Fish Dealer/Fishmonger/魚屋,
はなや:Florist/花屋,
ほんや:Bookstore/Bookshop/本屋,
パンヤ:Bakery/パン屋 (write YA katakana),
デパート:Department Store,
スーパー:Supermarket,
バー:Bar,
レストラン:Restaurant,
コンビニ:Convenience Store,
ペットショップ:Pet Shop,
てら:temple,
じんじゃ:shrine,
ぎんこう:bank,
がっこう:school/学校,
だいがく:university,
なら:place/period 710-794,
えど:place/period 1603 - 1868,
こうべ:place,
ぎんざ:place,
はこね:place,
なごや:Place,
まつしま:place,
ばしょ:place/location,
にっこう:place,
さっぽろ:place,
おおさか:place,
きょうと:place,
ほんしゅう:place,
とうきょう:place,

ほっかいどう:place_new,
とうほく:place_new,
かんとう:place_new,
ちゅうぶ:place_new,
かんさい:place_new,
ちゅうごく:place_new,
しこく:place_new,
きゅうしゅう:place_new,
ほんしゅう:place_new,







******* transport/travel *******,
くるま:Car/車,
タクシー:Taxi,
ジープ:Jeep,
バス:Bus,
ふね:ship,
ミニバス:Minibus,
トラック:Truck,
トラクター:Tractor,
バン:Van,
オートバイ:Motorcycle,
バイク:Motorcycle(Motorbike),
スクーター:Scooter,
ヘリコプター:Helicopter,
ロケット:Rocket,
でんしゃ:Train/電車,
モノレール:Monorail,
ボート:Boat,
クルーズ:Cruise,
えき:Station/駅,
ちかてつ:subway,
いりぐち:Entrance/入口,
でぐち:Exit/出口,
ホーム:Platform,
きっぷ:Ticket/切符,
たび:Travel/旅,
ツアー:Tour,
ホテル:Hotel,
カプセルホテル:Capsule Hotel,
ホステル:Hostel,
チェックイン:Check-in,
チェックアウト:Check-out,
パスポート:Passport,
ロッカー:Locker,
レンタカー:Rent-a-car/Hire Car,
ガイド:Tour Guide,
キャラバン:Caravan,





******* Objects & tools *******,
ペン:Pen,
えんぴつ:Pencil/鉛筆,
けしゴム:Eraser/消しゴム,
ノート:Notebook,
かみ:Paper/紙,
ほん:Book/本,
パレット:Palette,
え:Picture/Drawing/Painting/絵,
クレヨン:Crayon,
ホワイトボード:Whiteboard,
チョーク:Chalk,
カレンダー:Calendar,
しんぶん:newspaper,
ちず:map,
とけい:clock/watch,
つくえ:desk,
いす:chair,
かさ:umbrella,







******* Adjectives *******,
たのしい:Happy/楽しい[adj],
かなしい:Sad/悲しい[adj],
たかい:High/expensive/高い[adj],
やすい:Cheap/安い[adj],
はやい:Fast/early/早い[adj],
おそい:Slow/遅い[adj],
おいしい:Delicious/美味しい[adj],
あつい:Hot/熱い[adj],
あかるい:Bright/明るい[adj],
くらい:Dark/暗い[adj],
おおきい:Big/大きい[adj],
ちいさい:Small/小さい[adj],
あたらしい:New/新しい[adj],
ふるい:Old/古い[adj],
じょうず:Skillfull/Goodat/上手[adj],
へた:Unskillful/poor at/下手[adj],
ざんねん:Regrettable/Sorry/Pity/残念[adj],
きらい:dislike – adjective/嫌い[adj],
すき:like|adjective/好き[adj],
あるく:to walk/歩く[adj],







******** Pronouns *******,
わたし:I/私[zamir],
ぼく:I/me– used by boys/僕[zamir],
あなた:You[zamir],
かれ:He/him/彼[zamir],
かのじょ:She/her/彼女[zamir],
これ:This/it[zamir],
それ:That/it[zamir],
あれ:That/it (far from speaker)[referring to something that is distanced from the speaker][zamir],
どれ:which?[zamir],
ここ:here[zamir],
そこ:There[zamir],
あそこ:Over there[zamir],
どこ:where?[zamir],








******** Katakana N5 vocab *******,
アパート:apartment[kata],
バス:bus[kata],
バター:butter​[kata],
ベッド:bed[kata],
ボールペン:ball-point pen[kata],
ボタン:button[kata],
デパート:department store[kata],
ドア:door[kata],
エレベーター:elevator[kata],
フィルム:film[kata],
フォーク:fork[kata],
ギター:guitar[kata],
グラム:gram[kata],
ハンカチ:handkerchief​[kata],
ホテル:hotel[kata],
カメラ:camera[kata],
カップ:cup[kata],
カレー:curry[kata],
カレンダー:calendar[kata],
キログラム:kilogram[kata],
キロメートル:kilometer[kata],
コーヒー:Coffee[kata],
コート:coat[kata],
コピー:copy/photocopy[kata],
コップ:glass (drinking vessel)/tumbler​[kata],
クラス:class[kata],
マッチ:match[kata],
メートル:metre/meter[kata],
ナイフ:knife[kata],
ネクタイ:tie/necktie[kata],
ノート:notebook[kata],
ニュース:news[kata],
パーティー:party[kata],
パン:bread[kata],
ページ:page[kata],
ペン:pen[kata],
ペット:pet[kata],
ポケット:pocket[kata],
ポスト:post[kata],
プール:swimming pool[kata],
ラジオ:radio[kata],
レコード:record[kata],
レストラン:restaurant[kata],
セーター:sweater/jumper[kata],
シャツ:shirt[kata],
シャワー:shower[kata],
スカート:skirt[kata],
スポーツ:sport/sports[kata],
スプーン:spoon[kata],
スリッパ:slipper/slippers[kata],
ストーブ:heater/stove[kata],
タクシー:taxi[kata],
テーブル:table[kata],
テープ:tape[kata],
テープレコーダー:tape recorder[kata],
テレビ:television/TV​[kata],
テスト:examination/quiz/test[kata],
トイレ:toilet[kata],
ワイシャツ:shirt[kata],
ゼロ:zero[kata],
ズボン:trousers/pants[kata],";
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel='stylesheet' type='text/css' media='screen' href='style.css'>
</head>

<body class="index">

    <div class="kana-container">

        <form method="POST" action="result.php" class="input-form flex-wrap-around">

            <label for="string">لیست محصولات</label>
            <textarea name="string" rows="10" cols="30" ><?php echo $val; ?></textarea>

            <span>
                <label class="mode">مود</label>
                <input type="radio" id="hiragana" name="kana" value="hiragana" checked>
                <label for="hiragana">هیراگانا</label>
                <input type="radio" id="katakana" name="kana" value="katakana">
                <label for="katakana">کاتاکانا</label> 
            </span>
            
            <input type="submit" value="محاسبه">

        </form>
        
    </div>
    
</body>
</html>